name: Vulkan Guide

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ \
          git \
          libx11-dev \
          libxi-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libgl1-mesa-dev \
          libvulkan-dev \
          vulkan-tools

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Setup CMake
      uses: threeal/cmake-action@v2.1.0
      with:
        generator: Ninja

    - name: Compile program
      run: make release

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Move file
      run: mv bin/* .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-build-artifacts-linux
        path: |
          vulkan_guide
          libSDL3*
          start.sh
          assets/
          shaders/
        overwrite: true
